In [2]:
import numpy as np
import math

In [19]:
a = int(1/(0.002*1.25)/2)
b = np.sign(0.1)

In [16]:
def H_f(c,x):
    return 0.5*(np.sign(x-c)+1)*1

In [25]:
offset = np.array([0.5,0,0,0.5])
gait_regions = np.array([[-0.1,0.0,1.1], [-0.1,0.0,1.1], [-0.1,0.0,1.1], [-0.1,0.0,1.1]])
distr = 0.5
end = (offset + distr)%1.0
ranger = np.stack((offset, end), axis=-1)
print('end=', end)
print('ranger=', ranger)
comparison = (ranger[:,0]>ranger[:,1]).astype(int)
ranger.sort(axis=1)
print('comparison=', comparison)
print('new ranger=', ranger)
for i in range(4):
    gait_regions[i,comparison[i]:comparison[i]+2]=ranger[i]
print('gait_region=', gait_regions)
stance_timing = np.array([(1-distr),distr])
gait_exp = -((np.stack((end,offset),axis=-1)+stance_timing)%1.0)/stance_timing+1 # neutral_times_phases
print('gait_exp=', gait_exp)
t = 0.25*np.array((4,))
leg_states = (np.round(H_f(gait_regions[:,0],t)-H_f(gait_regions[:,1],t)+H_f(gait_regions[:,2],t))).astype(int)
print('leg_states=', leg_states)
leg_phase_timings = gait_exp*stance_timing
leg_states2 = np.array([1-leg_states,leg_states]).T
norm_delta_time = 5
leg_phase_timings = leg_states2*(leg_phase_timings+norm_delta_time)
leg_phase_timings_norm = leg_phase_timings/stance_timing
print('leg_phase_timings_norm=', leg_phase_timings_norm)

end= [0.  0.5 0.5 0. ]
ranger= [[0.5 0. ]
 [0.  0.5]
 [0.  0.5]
 [0.5 0. ]]
comparison= [1 0 0 1]
new ranger= [[0.  0.5]
 [0.  0.5]
 [0.  0.5]
 [0.  0.5]]
gait_region= [[-0.1  0.   0.5]
 [ 0.   0.5  1.1]
 [ 0.   0.5  1.1]
 [-0.1  0.   0.5]]
gait_exp= [[0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]]
leg_states= [1 0 0 1]
leg_phase_timings_norm= [[ 0. 11.]
 [11.  0.]
 [11.  0.]
 [ 0. 11.]]
