In [32]:
import numpy as np

x = np.array([[[-2,3,4], [3,-4,5]], [[-2,3,4], [3,-4,5]]])
out = 1 / (1 + np.exp(-np.array(x)))
print('x=', x)
print('out=', out)
print('max_x=', np.maximum(x, 0))
max_x = np.maximum(x, 0)
print('max_x_logi=', np.ones(np.shape(max_x))*(max_x>0))
print('plus=', x+np.array([[1], [2]]))
x_resh = x.reshape((x.shape[0], int(x.size/x.shape[0])))
print('reshape_of_x=', x_resh)
x_2 = np.array([[-2,3,4], [3,-4,5]])


x= [[[-2  3  4]
  [ 3 -4  5]]

 [[-2  3  4]
  [ 3 -4  5]]]
out= [[[0.11920292 0.95257413 0.98201379]
  [0.95257413 0.01798621 0.99330715]]

 [[0.11920292 0.95257413 0.98201379]
  [0.95257413 0.01798621 0.99330715]]]
max_x= [[[0 3 4]
  [3 0 5]]

 [[0 3 4]
  [3 0 5]]]
max_x_logi= [[[0. 1. 1.]
  [1. 0. 1.]]

 [[0. 1. 1.]
  [1. 0. 1.]]]
plus= [[[-1  4  5]
  [ 5 -2  7]]

 [[-1  4  5]
  [ 5 -2  7]]]
reshape_of_x= [[-2  3  4  3 -4  5]
 [-2  3  4  3 -4  5]]
